language: ruby

rvm:
  - "2.6"

services:
  - redis-server

gemfile:
  - Gemfile

matrix:
  include:
  - rvm: "2.6"
    gemfile: gemfiles/sidekiq_6.gemfile

  - rvm: "2.5"
    gemfile: gemfiles/sidekiq_5.gemfile

  - rvm: "2.5"
    gemfile: gemfiles/sidekiq_4.gemfile

  - rvm: "2.4"
    gemfile: gemfiles/sidekiq_3.gemfile

script:
  - gem list bundler
  - bundle exec rake spec
